### PR TITLE
#15 - Attempt to use distillery

### PR DESCRIPTION
**Pull request by rowpsmo1859**
Changelog
- Added check for Distillery
- Added Distillery dependency
- Removed Exrm dependency

### CODE REVIEW

**Review by asaaki — APPROVED** [review]
Looks great. Will merge it after the docker image is updated.

**Comment by mgwidmann** [comment]
was trying @JeremyBellows blog post and ran into this issue... Would be nice to merge this so others don't run into this problem...

**Comment by rowpsmo1859** [comment]
@mgwidmann Hey Matt! Thanks for dropping a comment on this!

Since this isn't merged yet, replace distillery with [exrm](https://github.com/bitwalker/exrm)

@asaaki How can I help with updating edib?

**Comment by asaaki** [comment]
Sorry for the delay. I was quite sick the last days and haven't touched any computer in the meantime.
I'm going to merge this PR and update the toolchain.

**Comment by rowpsmo1859** [comment]
@asaaki Oh no! Feel better!

**Comment by asaaki** [comment]
@JeremyBellows 

First of all: Thank you for the blog post and mentioning this project! 🙇 

In your [blog post](http://www.jeremybellows.com/blog/How-to-Create-a-Minimal-Phoenix-Elixir-Server-Docker-Image) could you update the following info?

``` diff
# mix task utilizing updated toolchain
- mix archive.install https://git.io/edib-0.8.1.ez
+ mix archive.install https://git.io/edib-0.9.0.ez
```

``` diff
# most recent distillery version
- {:distillery, "~> 0.9"}
+ {:distillery, "~> 0.10"}
```

Funfact: `mix release.init` outside of the build process is mandatory for now, since distillery requires a `rel/config.exs` to be present for the task `mix release`.

I think we should do this step in the build process if we could not find such file, so nobody has to do this by hand for an easy start. (The default config might be fine for people trying `edib` for the first time, I guess.)

**Comment by rowpsmo1859** [comment]
Ah! Good catch! I'll update the post today :+1: 

I thought about implementing the config generation but didn't so the user was knowledgeable of config. I'm not convinced the current status quo (forced manual generation) is the best approach so let's explore alternatives

**Comment by asaaki** [comment]
We can continue this specific topic at #21.

**Pull request merged**
