### PR TITLE
Issue#28 - Changed edib version to match docker edib tool commit. 

### PR DESCRIPTION
**Pull request by rowpsmo1859**
## Breaking Change
Needs Distillery 1.0+ to work

## Notes
This PR needs to be approved after the docker image edib/edib-tool:1.6.0 has been published

https://github.com/edib-tool/docker-edib-tool/pull/10
*I guessed at the versioning since the above PR has a breaking change. Let me know if this is wrong! :+1: *

### CODE REVIEW

**Comment by rowpsmo1859** [comment]
This PR depends on @luckynum7 PR https://github.com/edib-tool/docker-edib-tool/pull/9

I closed the other PR that I created erroneously

**Comment by rowpsmo1859** [comment]
I also added a `.gitattributes` file that will enforce line endings. Please let me know if this needs to be removed :)

**Comment by asaaki** [comment]
> I also added a .gitattributes file that will enforce line endings. Please let me know if this needs to be removed :)

Since the proposed changes are basically the default for Linux, MacOS and other unixoid systems I don't see anything harmful in adding this file if it makes your life easier. :man_shrugging:

**Comment by asaaki** [comment]
Could you also rebase onto current master? I have updated the codebase a bit, so I'd like to make sure there are no conflicts. (edib version in master changed)

**Comment by asaaki** [comment]
Conflicts resolved.

**Comment by rowpsmo1859** [comment]
Thanks for updating the branch! :+1:

**Pull request merged**
